databases:
  - name: elec-con-db
    databaseName: electricity
    user: academy
    plan: free

services:
  - type: web
    name: elec-con-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: elec-con-db
          property: connectionString

  - type: web
    name: elec-con-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://elec-con-backend.onrender.com
